version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/apps/globalwork/deploy
permissions:
  - object: /home/ubuntu/apps/globalwork/deploy
    owner: ubuntu
    group: ubuntu
    pattern: "*"
    mode: 777
    type:
      - file
      - directory
hooks:
  BeforeInstall:
    - location: deploy_scripts/arrange-deploy-folders.sh
      runas: root
  AfterInstall:
    - location: deploy_scripts/db-config.sh
      runas: ubuntu
    - location: deploy_scripts/install-gems.sh
      runas: ubuntu
    - location: deploy_scripts/compile-assets.sh
      runas: ubuntu
    - location: deploy_scripts/run-db-migrations.sh
      runas: ubuntu

  ApplicationStart:
    - location: deploy_scripts/application-start.sh
      runas: root